### ISSUE TITLE
Linear start and Random (time) noise

### ISSUE THREAD

**Issue by richielo** [sandrobarna/pytorch_memn2n#2]
As titled, may I ask if you experimented with Linear start and random noise injection? That was used in the original MemN2N paper and I am wondering how much of an impact they have on performance in these goal-oriented tasks

**Comment by sandrobarna** [comment]
No I didn't. It gave me pretty good result as it is on the task I built it for back in the days.

**Comment by richielo** [comment]
Got it. Thanks!
